# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_crawld'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_dest', models.TextField(blank=True, db_column='R_DEST', null=True)),
                ('arr_t', models.TextField(blank=True, db_column='ARR_T', null=True)),
                ('stop_num', models.TextField(blank=True, db_column='STOP_NUM', null=True)),
                ('dep_t', models.TextField(blank=True, db_column='DEP_T', null=True)),
                ('r_origin', models.TextField(blank=True, db_column='R_ORIGIN', null=True)),
                ('sch_cost', models.IntegerField(blank=True, db_column='SCH_COST', null=True)),
                ('l_lo', models.TextField(blank=True, db_column='L_LO', null=True)),
                ('f_time', models.TextField(blank=True, db_column='F_TIME', null=True)),
                ('arr_day', models.TextField(blank=True, db_column='ARR_DAY', null=True)),
                ('arr_d_week', models.TextField(blank=True, db_column='ARR_D_WEEK', null=True)),
                ('dep_day', models.TextField(blank=True, db_column='DEP_DAY', null=True)),
                ('dep_d_week', models.TextField(blank=True, db_column='DEP_D_WEEK', null=True)),
            ],
            options={
                'db_table': 'csv',
                'managed': False,
            },
        ),
    ]
