# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_Up_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=40)),
                ('number', models.IntegerField()),
                ('country', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
