# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_sign_up_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='eurail',
            fields=[
                ('eurail_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('R_ORIGIN', models.CharField(max_length=20)),
                ('R_DEST', models.CharField(max_length=20)),
                ('R_ORIGIN_CITY', models.CharField(max_length=20)),
                ('R_DEST_CITY', models.CharField(max_length=20)),
                ('DEP_DATE', models.DateField()),
                ('PRICE', models.IntegerField()),
                ('DEP_TIME', models.CharField(max_length=20)),
                ('ARR_TIME', models.CharField(max_length=20)),
                ('REQUIRED_TIME', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
    ]
